# Generated by Django 4.0.4 on 2022-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistroANS', models.IntegerField(max_length=10)),
                ('CNPJ', models.IntegerField(max_length=15)),
                ('RazaoSocial', models.CharField(max_length=200)),
                ('NomeFantasia', models.CharField(max_length=200)),
                ('Modalidade', models.CharField(max_length=100)),
                ('Logradouro', models.CharField(max_length=200)),
                ('Numero', models.CharField(max_length=50)),
                ('Complemento', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=200)),
                ('Cidade', models.CharField(max_length=200)),
                ('UF', models.CharField(max_length=2)),
                ('CEP', models.IntegerField(max_length=10)),
                ('DDD', models.IntegerField(max_length=2)),
                ('Telefone', models.IntegerField(max_length=15)),
                ('Fax', models.IntegerField(max_length=15)),
                ('Endereco', models.CharField(max_length=200)),
                ('Representante', models.CharField(max_length=200)),
                ('CargoRepresentante', models.CharField(max_length=200)),
                ('DataRegistroANS', models.DateTimeField()),
            ],
        ),
    ]
